language: cpp

sudo: required

addons:
  apt:
    source:
      - sourceline: 'ppa:george-edison55/cmake-3.x'
    packages:
      - cmake

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake .. && make
  - ./hikaru_test
  - ./hikaru_sample
